import { StyleSheet, Platform } from 'react-native';

const isTV = Platform.isTV;

export const styles = StyleSheet.create({
  root: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#000',
  },
  center: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 16,
  },
  loadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#000',
    zIndex: 100,
  },
  infoTxt: {
    color: '#aaa',
    fontSize: isTV ? 16 : 13,
    marginTop: 8,
  },
  errorTxt: {
    color: '#e50914',
    fontSize: 14,
    textAlign: 'center',
    paddingHorizontal: 32,
  },
  retryBtn: {
    backgroundColor: '#e50914',
    borderRadius: 24,
    paddingHorizontal: 28,
    paddingVertical: 10,
  },
  retryTxt: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 14,
  },
  seekOverlay: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 200,
  },
  seekBalloon: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.65)',
    paddingHorizontal: 22,
    paddingVertical: 12,
    borderRadius: 30,
    gap: 8,
  },
  seekBalloonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  toastOverlay: {
    position: 'absolute',
    top: 80,
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(20, 20, 24, 0.92)',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(255, 214, 10, 0.4)',
    gap: 8,
    zIndex: 105,
  },
  toastText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '600',
  },
  turboBanner: {
    position: 'absolute',
    top: 40,
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.75)',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    zIndex: 9999,
    gap: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.5,
    shadowRadius: 4,
    elevation: 10,
  },
  turboText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  cornerResizeGrip: {
    position: 'absolute',
    top: 6,
    left: 6,
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: 'rgba(0, 0, 0, 0.65)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 999999,
  },
  errorTxtTV: {
    color: '#e50914',
    fontSize: 18,
    textAlign: 'center',
    paddingHorizontal: 32,
  },
  retryBtnTV: {
    backgroundColor: '#e50914',
    borderRadius: 24,
    paddingHorizontal: 48,
    paddingVertical: 20,
  },
  retryTxtTV: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 18,
  },
  tvGradientTop: {
    ...StyleSheet.absoluteFillObject,
  },
  tvGradientBottom: {
    ...StyleSheet.absoluteFillObject,
  },
  tvLoadingText: {
    fontSize: 22,
    color: '#fff',
    marginTop: 20,
  },
});
